trait Max {
  fn max() -> Self;
  fn double(self) -> Self;
  fn add(self, other: Self) -> Self;
}

impl Max for u8 {
  fn max() -> u8 {
    let x: Self = u8(255)
    return x
  }

  fn double(self) -> Self {
    return self * 2
  }

  fn add(self, other: Self) -> u8 {
    return self + other
  }
}

contract Example {
  pub fn run_test(self) {
    assert u8::max() == 255
    // TODO: We should not need the cast
    assert u8(u8(1).double()) == 2
    assert 1.add(2) == 3
  }

}

