[package]
name = "fe"
version = "0.0.1"
authors = ["David Sanders <david@ethereum.org>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/ethereum/fe"
description = "An implementation of the Fe smart contract language"
keywords = ["ethereum", "fe", "yul", "smart", "contract", "compiler"]
categories = ["cryptography::cryptocurrencies", "command-line-utilities", "development-tools"]
readme = "README.md"

[workspace]
members = [".", "parser", "compiler"]

[features]
solc-backend = ["fe-compiler/solc-backend"]

[dependencies]
fe-parser = {path = "parser", version = "0.0.1"}
fe-compiler = {path = "compiler", version = "0.0.1"}
clap = "2.33.3"
