use std::evm::StorageMap

msg Msg {
    #[selector = 0]
    Get -> u256,
}

fn get_balance(addr: u256) -> u256
    uses (balances: StorageMap<u256, u256>)
{
    balances.get(key: addr)
}

fn set_balance(addr: u256, value: u256)
    uses (balances: mut StorageMap<u256, u256>)
{
    balances.set(key: addr, value)
}

contract C {
    mut balances: StorageMap<u256, u256>

    recv Msg {
        Get -> u256 uses (mut balances) {
            with (mut balances) {
                set_balance(addr: 1, value: 2)
            }
            with (balances) {
                get_balance(addr: 1)
            }
        }
    }
}
